"""
IDCFSS - Pipeline Exporter Module
Exports preprocessing configuration as JSON and generates reproducible Python code.
"""
import json
from typing import List, Dict, Any


class PipelineExporter:
    def __init__(self):
        self.steps: List[Dict[str, Any]] = []

    def add_step(self, module: str, method: str, columns: list, params: dict = None):
        self.steps.append({
            "module": module,
            "method": method,
            "columns": columns,
            "params": params or {}
        })

    def to_json(self) -> str:
        return json.dumps({"pipeline": self.steps, "version": "1.0"}, indent=2)

    def to_python_code(self) -> str:
        lines = [
            "# IDCFSS - Auto-generated Preprocessing Pipeline",
            "# Generated by IDCFSS v1.0",
            "",
            "import pandas as pd",
            "import numpy as np",
            "from sklearn.impute import KNNImputer",
            "from sklearn.experimental import enable_iterative_imputer  # noqa",
            "from sklearn.impute import IterativeImputer",
            "from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler, LabelEncoder",
            "from sklearn.ensemble import IsolationForest",
            "",
            "",
            "def preprocess(df: pd.DataFrame) -> pd.DataFrame:",
            '    """Apply the full preprocessing pipeline."""',
            "    df = df.copy()",
            "",
        ]
        for step in self.steps:
            mod = step["module"]
            method = step["method"]
            cols = step["columns"]

            if mod == "missing" and method == "mean":
                for col in cols:
                    lines.append(f"    df['{col}'] = df['{col}'].fillna(df['{col}'].mean())")
            elif mod == "missing" and method == "median":
                for col in cols:
                    lines.append(f"    df['{col}'] = df['{col}'].fillna(df['{col}'].median())")
            elif mod == "missing" and method == "mode":
                for col in cols:
                    lines.append(f"    df['{col}'] = df['{col}'].fillna(df['{col}'].mode()[0])")
            elif mod == "missing" and method == "knn":
                k = step.get("params", {}).get("k", 5)
                cols_str = str(cols)
                lines.append(f"    imputer = KNNImputer(n_neighbors={k})")
                lines.append(f"    df[{cols_str}] = imputer.fit_transform(df[{cols_str}])")
            elif mod == "outlier" and method == "cap":
                for col in cols:
                    lines.append(f"    q1, q3 = df['{col}'].quantile(0.25), df['{col}'].quantile(0.75)")
                    lines.append(f"    iqr = q3 - q1")
                    lines.append(f"    df['{col}'] = df['{col}'].clip(q1 - 1.5*iqr, q3 + 1.5*iqr)")
            elif mod == "encoding" and method == "label":
                for col in cols:
                    lines.append(f"    le_{col} = LabelEncoder()")
                    lines.append(f"    df['{col}'] = le_{col}.fit_transform(df['{col}'].astype(str))")
            elif mod == "encoding" and method == "onehot":
                cols_str = str(cols)
                lines.append(f"    df = pd.get_dummies(df, columns={cols_str}, drop_first=False)")
            elif mod == "scaling" and method == "minmax":
                cols_str = str(cols)
                lines.append(f"    scaler = MinMaxScaler()")
                lines.append(f"    df[{cols_str}] = scaler.fit_transform(df[{cols_str}])")
            elif mod == "scaling" and method == "standard":
                cols_str = str(cols)
                lines.append(f"    scaler = StandardScaler()")
                lines.append(f"    df[{cols_str}] = scaler.fit_transform(df[{cols_str}])")
            elif mod == "scaling" and method == "robust":
                cols_str = str(cols)
                lines.append(f"    scaler = RobustScaler()")
                lines.append(f"    df[{cols_str}] = scaler.fit_transform(df[{cols_str}])")
            elif mod == "feature_selection":
                cols_str = str(cols)
                lines.append(f"    selected_features = {cols_str}")
                lines.append(f"    df = df[selected_features]")
            lines.append("")

        lines.append("    return df")
        lines.append("")
        lines.append("")
        lines.append("if __name__ == '__main__':")
        lines.append("    df_raw = pd.read_csv('your_dataset.csv')")
        lines.append("    df_clean = preprocess(df_raw)")
        lines.append("    df_clean.to_csv('cleaned_dataset.csv', index=False)")
        lines.append("    print(f'Cleaned: {df_clean.shape}')")
        return "\n".join(lines)
